version: '2'
services:
  msprmaintenanceevolutiveapp-app:
    image: msprmaintenanceevolutiveapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://msprmaintenanceevolutiveapp-postgresql:5432/msprMaintenanceEvolutiveApp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  msprmaintenanceevolutiveapp-postgresql:
    extends:
      file: postgresql.yml
      service: msprmaintenanceevolutiveapp-postgresql
