version: '2'
services:
  msprmaintenanceevolutiveapp-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/msprMaintenanceEvolutiveApp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=msprMaintenanceEvolutiveApp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
